-- Analytics → content drafts (Know/Understand → Spread inbox)
CREATE TABLE IF NOT EXISTS analytics_content_drafts (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  organization_id BIGINT NULL,
  conversation_id VARCHAR(64) NULL,
  survey_id BIGINT NULL,
  draft_kind ENUM('chart_post', 'explainer_video', 'candidate_clip') NOT NULL,
  title VARCHAR(255) NOT NULL,
  claim TEXT NOT NULL,
  honest_caveat TEXT NULL,
  suggested_angle VARCHAR(512) NULL,
  flag ENUM('publishable', 'directional_only') NOT NULL DEFAULT 'directional_only',
  caption TEXT NULL,
  script_json JSON NULL,
  blurb TEXT NULL,
  figure_storage_key VARCHAR(512) NULL,
  figure_media_url VARCHAR(1024) NULL,
  figure_caption VARCHAR(512) NULL,
  sample_n INT NULL,
  source_line VARCHAR(512) NULL,
  status ENUM('ready', 'opened', 'staged', 'used', 'dismissed') NOT NULL DEFAULT 'ready',
  payload JSON NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_acd_user (user_id),
  INDEX idx_acd_org (organization_id),
  INDEX idx_acd_conversation (conversation_id),
  INDEX idx_acd_status (status),
  CONSTRAINT fk_acd_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
