'use client';

import { useEffect, useRef, useState } from 'react';
import { toast } from 'react-hot-toast';
import Image from 'next/image';
import {
    Dialog,
    DialogContent,
    DialogDescription,
    DialogHeader,
    DialogTitle,
    DialogFooter,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Button } from "@heroui/button";
import { Textarea } from "@/components/ui/textarea";
import { Progress } from "@/components/ui/progress";
import { Loader2 } from "lucide-react";

// Helper function to get available categories
// const getCategories = () => {
//     try {
//         // Check if we can access the categories from window (client-side)
//         return typeof window !== 'undefined' && window?.__NEXT_DATA__?.props?.pageProps?.categories || [];
//     } catch (error) {
//         return [];
//     }
// };

const AgentProfileDialog = ({
    isOpen,
    onClose,
    name,
    description,
    image,
    isSubmittingProfile,
    handleSaveProfile
}: {
    isOpen: boolean;
    onClose: () => void;
    name: string;
    description: string;
    image: string;
    isSubmittingProfile: boolean;
    handleSaveProfile: (name: string, description: string, fileRef: React.RefObject<HTMLInputElement>, imagePreview: string) => void;
}) => {
    const [agentName, setAgentName] = useState(name);
    const [agentDescription, setAgentDescription] = useState(description);
    const fileRef = useRef<HTMLInputElement | null>(null);
    const [imagePreview, setImagePreview] = useState<string>(image);
    const [imageError, setImageError] = useState(false);
    const [isGenerating, setIsGenerating] = useState(false);
    const [hasAutoGenerated, setHasAutoGenerated] = useState(false);
    const [hasMounted, setHasMounted] = useState(false);

    // Set mounted state
    useEffect(() => {
        setHasMounted(true);
    }, []);

    // Update state when props change
    useEffect(() => {
        setAgentName(name);
        setAgentDescription(description);
        setImagePreview(image);
        setImageError(false);
        
        // Reset auto-generation state when dialog reopens
        if (isOpen) {
            setHasAutoGenerated(false);
        }
    }, [name, description, image, isOpen]);
    
    // Auto-generate profile when dialog opens with empty fields
    useEffect(() => {
        if (!hasMounted) return;
        
        if (isOpen && !hasAutoGenerated) {
            console.log("Auto-generating profile...");
            setHasAutoGenerated(true);
            generateAgentProfile();
        }
    }, [isOpen, hasAutoGenerated, hasMounted]);

    const handleImageUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
        const file = e.target.files?.[0];
        if (file) {
            const reader = new FileReader();
            reader.onloadend = () => {
                setImagePreview(reader.result as string);
                setImageError(false);
            };
            reader.readAsDataURL(file);
        }
    };

    const handleImageError = () => {
        console.log("Image failed to load, using fallback");
        setImageError(true);
    };
    
    const generateAgentProfile = async () => {
        setIsGenerating(true);
        try {
            const category = "General";
            const interests: string[] = [];
            
            let generatedProfile = null;
            
            try {
                const response = await fetch('/api/generateAgentProfile', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                    },
                    body: JSON.stringify({ category, interests }),
                });
                
                const data = await response.json();
                
                if (data.status && data.profile) {
                    generatedProfile = data.profile;
                }
            } catch (apiError) {
                console.error("API call failed:", apiError);
            }
            
            if (!generatedProfile) {
                generatedProfile = {
                    name: "Market Maven",
                    description: "A strategic prediction agent that analyzes trends and makes calculated bets based on market patterns and historical data.",
                    avatarPrompt: "A robot with glasses analyzing charts and data"
                };
            }
            
            setAgentName(generatedProfile.name);
            setAgentDescription(generatedProfile.description);
            
            let avatarUrl = null;
            
            try {
                const avatarResponse = await fetch('/api/generateAgentAvatar', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                    },
                    body: JSON.stringify({
                        name: generatedProfile.name,
                        category,
                        avatarPrompt: generatedProfile.avatarPrompt,
                    }),
                });
                
                const avatarData = await avatarResponse.json();
                
                if (avatarData.status && avatarData.avatarUrl) {
                    avatarUrl = avatarData.avatarUrl;
                }
            } catch (avatarError) {
                console.error("Avatar API call failed:", avatarError);
            }
            
            if (!avatarUrl) {
                const formattedName = generatedProfile.name.replace(/\s+/g, '-').toLowerCase();
                avatarUrl = `https://api.dicebear.com/7.x/bottts/svg?seed=${formattedName}`;
            }
            
            setImagePreview(avatarUrl);
            setImageError(false);
            
            if (!hasAutoGenerated) {
                toast.success("AI profile generated!");
            }
        } catch (error) {
            console.error("Error generating agent profile:", error);
            
            setAgentName("Market Predictor");
            setAgentDescription("An AI agent that analyzes data and makes predictions on various market outcomes.");
            setImagePreview("https://api.dicebear.com/7.x/bottts/svg?seed=fallback-agent");
            
            if (!hasAutoGenerated) {
                toast.error("Something went wrong, using default profile");
            }
        } finally {
            setIsGenerating(false);
        }
    };

    return (
        <Dialog open={isOpen} onOpenChange={(open: boolean) => !open && onClose()}>
            <DialogContent className="sm:max-w-[425px] bg-background border-border">
                <DialogHeader>
                    <DialogTitle>Create Your Agent Profile</DialogTitle>
                    <DialogDescription>
                        Step 1 of 3: Let&apos;s set up your prediction agent&apos;s identity
                    </DialogDescription>
                    <Progress value={33} className="h-2" />
                </DialogHeader>

                <div className="space-y-6 py-4">
                    {/* AI Generation Button */}
                    <Button 
                        variant="solid"
                        onPress={() => {
                            setHasAutoGenerated(true);
                            generateAgentProfile();
                        }}
                        disabled={isGenerating || isSubmittingProfile}
                        className="w-full relative bg-purple-600 hover:bg-purple-700 text-white"
                    >
                        {isGenerating ? (
                            <div className="flex items-center justify-center gap-2">
                                <Loader2 className="h-4 w-4 animate-spin" />
                                <span>Generating AI Profile...</span>
                            </div>
                        ) : (
                            <div className="flex items-center justify-center gap-2">
                                <svg 
                                    width="18" 
                                    height="18" 
                                    viewBox="0 0 24 24" 
                                    fill="none" 
                                    xmlns="http://www.w3.org/2000/svg"
                                    className="text-white"
                                >
                                    <path d="M12 3L16 7M12 3L8 7M12 3V15M21 11V17C21 19.2091 19.2091 21 17 21H7C4.79086 21 3 19.2091 3 17V11" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
                                </svg>
                                <span>Generate AI Profile</span>
                            </div>
                        )}
                    </Button>

                    {/* Profile Image */}
                    <div className="flex flex-col items-center space-y-4">
                        <div className="relative w-24 h-24 rounded-full overflow-hidden border-2 border-border">
                            {imagePreview ? (
                                <Image
                                    src={imagePreview}
                                    alt="Agent avatar"
                                    fill
                                    className="object-cover"
                                    onError={handleImageError}
                                />
                            ) : (
                                <div className="w-full h-full bg-muted flex items-center justify-center">
                                    <svg className="w-8 h-8 text-muted-foreground" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
                                    </svg>
                                </div>
                            )}
                        </div>
                        <input
                            type="file"
                            ref={fileRef}
                            onChange={handleImageUpload}
                            accept="image/*"
                            className="hidden"
                        />
                        <Button
                            variant="bordered"
                            onPress={() => fileRef.current?.click()}
                            disabled={isSubmittingProfile}
                        >
                            Upload Image
                        </Button>
                    </div>

                    {/* Name Input */}
                    <div className="space-y-2">
                        <label htmlFor="name" className="text-sm font-medium">
                            Agent Name
                        </label>
                        <Input
                            id="name"
                            value={agentName}
                            onChange={(e) => setAgentName(e.target.value)}
                            placeholder="Enter your agent's name"
                            disabled={isSubmittingProfile}
                        />
                    </div>

                    {/* Description Input */}
                    <div className="space-y-2">
                        <label htmlFor="description" className="text-sm font-medium">
                            Description
                        </label>
                        <Textarea
                            id="description"
                            value={agentDescription}
                            onChange={(e) => setAgentDescription(e.target.value)}
                            placeholder="Describe your agent's personality and expertise"
                            disabled={isSubmittingProfile}
                            className="min-h-[100px]"
                        />
                    </div>
                </div>

                <DialogFooter>
                    <Button
                        variant="bordered"
                        onPress={onClose}
                        disabled={isSubmittingProfile}
                    >
                        Cancel
                    </Button>
                    <Button
                        onPress={() => handleSaveProfile(agentName, agentDescription, fileRef, imagePreview)}
                        disabled={isSubmittingProfile || !agentName || !agentDescription}
                    >
                        {isSubmittingProfile ? (
                            <div className="flex items-center gap-2">
                                <Loader2 className="h-4 w-4 animate-spin" />
                                <span>Saving...</span>
                            </div>
                        ) : (
                            "Save Profile"
                        )}
                    </Button>
                </DialogFooter>
            </DialogContent>
        </Dialog>
    );
};

export default AgentProfileDialog;