import {
    Modal,
    ModalContent,
    ModalHeader,
    ModalBody,
    ModalFooter,
} from "@heroui/modal";
import { Input, Textarea } from "@heroui/input";
import { Button } from "@heroui/button";
import { useRef, useState, useEffect } from "react";
import Image from "next/image";
import { Spinner } from "@heroui/spinner";
import toast from "react-hot-toast";

// Helper function to get available categories
// const getCategories = () => {
//     try {
//         // Check if we can access the categories from window (client-side)
//         return typeof window !== 'undefined' && window?.__NEXT_DATA__?.props?.pageProps?.categories || [];
//     } catch (error) {
//         return [];
//     }
// };

const AgentProfileDialog = (
    { isOpen, onClose, name, description, image, isSubmittingProfile, handleSaveProfile }:
        {
            isOpen: boolean, onClose: () => void, name: string, description: string, image: string,
            isSubmittingProfile: boolean, handleSaveProfile: (name: string, description: string, fileRef: React.RefObject<HTMLInputElement | null>, imagePreview: string) => Promise<void>
        }
) => {
    const [agentName, setAgentName] = useState(name);
    const [agentDescription, setAgentDescription] = useState(description);
    const fileRef = useRef<HTMLInputElement | null>(null);
    const [imagePreview, setImagePreview] = useState<string>(image);
    const [imageError, setImageError] = useState(false);
    const [isGenerating, setIsGenerating] = useState(false);
    const [hasAutoGenerated, setHasAutoGenerated] = useState(false);
    const [hasMounted, setHasMounted] = useState(false);

    // Set mounted state
    useEffect(() => {
        setHasMounted(true);
    }, []);

    // Update state when props change
    useEffect(() => {
        setAgentName(name);
        setAgentDescription(description);
        setImagePreview(image);
        setImageError(false);
        
        // Reset auto-generation state when dialog reopens
        if (isOpen) {
            setHasAutoGenerated(false);
        }
    }, [name, description, image, isOpen]);
    
    // Auto-generate profile when dialog opens with empty fields
    useEffect(() => {
        if (!hasMounted) return;
        
        // Force generation on first mount regardless of description state
        if (isOpen && !hasAutoGenerated) {
            console.log("Auto-generating profile...");
            setHasAutoGenerated(true);
            generateAgentProfile();
        }
    }, [isOpen, hasAutoGenerated, hasMounted]);

    const handleImageUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
        const file = e.target.files?.[0];
        if (file) {
            const reader = new FileReader();
            reader.onloadend = () => {
                setImagePreview(reader.result as string);
                setImageError(false);
            };
            reader.readAsDataURL(file);
        }
    };

    const handleImageError = () => {
        console.log("Image failed to load, using fallback");
        setImageError(true);
    };
    
    // Generate an AI profile
    const generateAgentProfile = async () => {
        setIsGenerating(true);
        try {
            // Default category and interests
            const category = "General";
            const interests: string[] = [];
            
            console.log("Calling generateAgentProfile API...");
            
            let generatedProfile = null;
            
            try {
                // Try calling API to generate profile
                const response = await fetch('/api/generateAgentProfile', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                    },
                    body: JSON.stringify({ category, interests }),
                });
                
                const data = await response.json();
                console.log("Profile generation response:", data);
                
                if (data.status && data.profile) {
                    generatedProfile = data.profile;
                }
            } catch (apiError) {
                console.error("API call failed:", apiError);
            }
            
            // If API failed, use hardcoded fallback
            if (!generatedProfile) {
                console.log("Using fallback profile generation");
                generatedProfile = {
                    name: "Market Maven",
                    description: "A strategic prediction agent that analyzes trends and makes calculated bets based on market patterns and historical data.",
                    avatarPrompt: "A robot with glasses analyzing charts and data"
                };
            }
            
            // Set name and description from either API or fallback
            setAgentName(generatedProfile.name);
            setAgentDescription(generatedProfile.description);
            
            // Now get a matching avatar
            let avatarUrl = null;
            
            try {
                console.log("Calling generateAgentAvatar API...");
                const avatarResponse = await fetch('/api/generateAgentAvatar', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                    },
                    body: JSON.stringify({
                        name: generatedProfile.name,
                        category,
                        avatarPrompt: generatedProfile.avatarPrompt,
                    }),
                });
                
                const avatarData = await avatarResponse.json();
                console.log("Avatar generation response:", avatarData);
                
                if (avatarData.status && avatarData.avatarUrl) {
                    avatarUrl = avatarData.avatarUrl;
                }
            } catch (avatarError) {
                console.error("Avatar API call failed:", avatarError);
            }
            
            // If avatar API failed, use fallback
            if (!avatarUrl) {
                console.log("Using fallback avatar");
                // Generate a basic DiceBear URL with the name as seed
                const formattedName = generatedProfile.name.replace(/\s+/g, '-').toLowerCase();
                avatarUrl = `https://api.dicebear.com/7.x/bottts/svg?seed=${formattedName}`;
            }
            
            setImagePreview(avatarUrl);
            setImageError(false);
            
            if (!hasAutoGenerated) {
                // Only show toast for manual generation, not auto-generation
                toast.success("AI profile generated!");
            }
        } catch (error) {
            console.error("Error generating agent profile:", error);
            
            // Fallback in case of any errors
            setAgentName("Market Predictor");
            setAgentDescription("An AI agent that analyzes data and makes predictions on various market outcomes.");
            setImagePreview("https://api.dicebear.com/7.x/bottts/svg?seed=fallback-agent");
            
            if (!hasAutoGenerated) {
                // Only show error toast for manual generation
                toast.error("Something went wrong, using default profile");
            }
        } finally {
            setIsGenerating(false);
        }
    };

    return (
        <Modal
            isOpen={isOpen}
            onClose={onClose}
            size="md"
            isDismissable={false}
            classNames={{
                base: "bg-[#1c1c1c] dark",
            }}
        >
            <ModalContent>
                <ModalHeader className="text-white">Profile Information</ModalHeader>
                <ModalBody>
                    {/* AI Generation Button */}
                    <div className="mb-4 flex justify-center">
                        <Button 
                            color="secondary"
                            onPress={() => {
                                setHasAutoGenerated(true); // Mark as manually generated
                                generateAgentProfile();
                            }}
                            isDisabled={isGenerating || isSubmittingProfile}
                            className="bg-purple-600 hover:bg-purple-700 transition-colors w-full relative"
                        >
                            {isGenerating ? (
                                <div className="flex items-center justify-center gap-2">
                                    <Spinner size="sm" color="white" />
                                    <span>Generating AI Profile...</span>
                                </div>
                            ) : (
                                <div className="flex items-center justify-center gap-2">
                                    <svg 
                                        width="18" 
                                        height="18" 
                                        viewBox="0 0 24 24" 
                                        fill="none" 
                                        xmlns="http://www.w3.org/2000/svg"
                                        className="text-white"
                                    >
                                        <path d="M12 3L16 7M12 3L8 7M12 3V15M21 11V17C21 19.2091 19.2091 21 17 21H7C4.79086 21 3 19.2091 3 17V11" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
                                    </svg>
                                    <span>Generate New AI Profile</span>
                                </div>
                            )}
                        </Button>
                    </div>

                    {/* Avatar Upload */}
                    <div className="flex flex-col items-center gap-4 mb-8">
                        <div
                            className="relative w-[120px] h-[120px] rounded-full overflow-hidden border border-white/10 cursor-pointer bg-[#2c2c2c] flex items-center justify-center"
                            onClick={() => fileRef.current?.click()}
                        >
                            {imagePreview && !imageError ? (
                                <div className="relative w-full h-full">
                                    {isGenerating && (
                                        <div className="absolute inset-0 flex items-center justify-center bg-black/50 z-10">
                                            <Spinner size="md" color="white" />
                                        </div>
                                    )}
                                    <Image
                                        src={imagePreview}
                                        alt="Agent Avatar"
                                        fill
                                        className="object-cover"
                                        onError={handleImageError}
                                    />
                                </div>
                            ) : (
                                <div className="w-full h-full flex items-center justify-center bg-blue-600 text-white">
                                    {isGenerating ? (
                                        <Spinner size="md" color="white" />
                                    ) : (
                                        agentName?.charAt(0)?.toUpperCase() || "+"
                                    )}
                                </div>
                            )}
                        </div>
                        <Button
                            color="primary"
                            onPress={() => fileRef.current?.click()}
                            size="sm"
                            className="bg-blue-500"
                        >
                            Change Avatar
                        </Button>
                        <input
                            type="file"
                            accept="image/*"
                            ref={fileRef}
                            className="hidden"
                            onChange={handleImageUpload}
                        />
                    </div>

                    {/* Form Fields */}
                    <div className="space-y-4">
                        <Input
                            label="Name"
                            value={agentName}
                            onChange={(e) => setAgentName(e.target.value)}
                            classNames={{
                                input: "bg-[#2c2c2c] text-white",
                                label: "text-white/60",
                            }}
                            isDisabled={isGenerating}
                        />
                        <Textarea
                            label="Description"
                            value={agentDescription}
                            onChange={(e) => setAgentDescription(e.target.value)}
                            classNames={{
                                input: "bg-[#2c2c2c] text-white",
                                label: "text-white/60",
                            }}
                            isDisabled={isGenerating}
                        />
                    </div>
                </ModalBody>
                <ModalFooter>
                    <Button
                        color="primary"
                        onPress={() => {
                            handleSaveProfile(agentName, agentDescription, fileRef, imagePreview);
                            // Close the dialog after saving
                            onClose();
                        }}
                        className="bg-blue-500"
                        isLoading={isSubmittingProfile}
                        isDisabled={isGenerating}
                    >
                        {isSubmittingProfile ? "Saving..." : "Save & Continue"}
                    </Button>
                </ModalFooter>
            </ModalContent>
        </Modal>
    )
}

export default AgentProfileDialog;