name: Deploy to Digital Ocean

on:
  push:
    branches: [ main ]  # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '23'
        cache: 'npm'
    
    - name: Install Dependencies
      run: npm ci
    
    - name: Build
      run: npm run build
      env:
        # Add your environment variables here
        NODE_ENV: production
        JWT_SECRET=51263e42bf327f3fc0a94be97aab48962a96c5ad53de61554db3d0fd2a763e4b2d254747ca08f27b94addffaa87a7f12481a3f6155eee090727dbd07bc843d13
        NEXT_PUBLIC_APP_URL=https://getantelope.com
        ENVIRONMENT_MODE=dev

        OPENAI_API_KEY=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
        DEEPSEEK_API_KEY=sk-720e035cec0348da9091de83ee20ee74
        GEMINI_API_KEY=AIzaSyBDX14yiy3RBP6Dwdb5qh_UTdBIpUmti8g
        SERPAPI_API_KEY=9079d9c39ef424f205b1e9aad4916e0b12b7aae99e22012af354dc2ec9e20620
        PINECONE_API_KEY=pcsk_3KDfm_SHcxsjyxiDueis9j66qYdns6X3QAtj5Km8a31QLxcmYgwXN9iq2XhYWaJpWebgE
        COINMARKETCAP_API_KEY=26b8af22-d6ee-4b9d-86f1-c239780a8be1
        TELEGRAM_BOT_TOKEN=7923899126:AAHykD2VqqJbsU-9wIah8jIbXCswfXtFcCA
        TELEGRAM_BOT_USERNAME=@AntelopeTerminal_Bot
        TELEGRAM_CHANNEL_ID=-1002331915016
        HOUSE_FEE_RATE=1

        CREDIT_BALANCE=1000

        ESCROW_SOLANA_ADDRESS=D22aL5rfqa9RUZYxqN1V4JEiV4onRkeFz9ZHGasR69RP
        ESCROW_SOLANA_PRIVATE=3tBnGVgRrpB76rdZTSUBtQuumXxKmQVazBzrwf8GDEfUp6oYyTneKmmmf6xL4qeEtwWWqqVMWkNFaQpjGd6E3yru

        STRIPE_SECRET_KEY=sk_test_UChzMFf1YS5WXTEurmwNFCB500QYpwgITG
        STRIPE_PUBLIC_KEY=pk_test_fOn2bQ8uU6d2dioXM6MIbctY00V0uFWyhX
        STRIPE_SECRET_WEBHOOK_KEY=whsec_7wW4pArUT94PP5onTL2OZzYtZXuYVC0i
        SPORTS_DB_API_KEY=995836

        PINATA_KEY=f0fe7a1b24c564b30419
        PINATA_SECRET=ea0afaa745b49799c13f446c1293525ad717e498d6ee95505e91d6fa12b6cda2
        PINATA_JWT=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySW5mb3JtYXRpb24iOnsiaWQiOiI2ZTM5ZjJkYi1jYTFlLTQ0NTMtYjYyNC02Nzk1M2QwYjIxZDkiLCJlbWFpbCI6InRob21hc0BmaXJzdHByaW5jaXBsZS5jbyIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJwaW5fcG9saWN5Ijp7InJlZ2lvbnMiOlt7ImRlc2lyZWRSZXBsaWNhdGlvbkNvdW50IjoxLCJpZCI6IkZSQTEifSx7ImRlc2lyZWRSZXBsaWNhdGlvbkNvdW50IjoxLCJpZCI6Ik5ZQzEifV0sInZlcnNpb24iOjF9LCJtZmFfZW5hYmxlZCI6ZmFsc2UsInN0YXR1cyI6IkFDVElWRSJ9LCJhdXRoZW50aWNhdGlvblR5cGUiOiJzY29wZWRLZXkiLCJzY29wZWRLZXlLZXkiOiJmMGZlN2ExYjI0YzU2NGIzMDQxOSIsInNjb3BlZEtleVNlY3JldCI6ImVhMGFmYWE3NDViNDk3OTljMTNmNDQ2YzEyOTM1MjVhZDcxN2U0OThkNmVlOTU1MDVlOTFkNmZhMTJiNmNkYTIiLCJleHAiOjE3NjQ0Mzk1OTZ9.4kattSZSM4E7bxIA2mXOls0lzW4BpDd16ZK_avSJHh4
        PINATA_GATEWAY=gateway.pinata.cloud

        MYSQL_HOST=antelopedb-do-user-18192858-0.j.db.ondigitalocean.com
        MYSQL_PORT=25060
        MYSQL_USER=doadmin
        MYSQL_PASSWORD=AVNS_Zobsi59qAR_OQ9QGwDd
        MYSQL_DATABASE=defaultdb

        AUTH_SECRET="pe+OO0kAj6wg2ZOQjjaYrBN1RXDjbFTFwhSm7TNXy+Q="
        AUTH_DISCORD_ID=1344845086437150771
        AUTH_DISCORD_SECRET=ujL9PRHg7rM9i8TjzmNTEwBkejspalEp
    
    - name: Deploy to Digital Ocean
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DROPLET_HOST }}
        username: ${{ secrets.DROPLET_USERNAME }}
        key: ${{ secrets.DROPLET_SSH_KEY }}
        script: |
          cd marketmaker  # Update this to your app's path on the server
          git pull origin main
          npm ci
          npm run build
          pm2 restart 7  # Update this to match your PM2 process name 